### ISSUE TITLE
frida.TimedOutError: unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by Miller1990** [frida/frida-python#102]
Hi,
I'm  trying  to use the follow instruction to get traffic generated by application for example "com.atebits.Tweetie2":
**frida-trace -U -f com.atebits.Tweetie2 -i open**
OR 
 **import frida
 device = frida.get_usb_device()
 pid = device.spawn(["com.atebits.Tweetie2"])**

Application start, but after few second return this error:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../frida/lib/python3.5/site-packages/frida/core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.TimedOutError: unexpectedly timed out while waiting for app to launch**

I'm using a OS X with : python 3.51, last version of frida and device iOS with 7.1 (32bit) 

Thanks Marco

**Comment by TankTheFrank** [comment]
Still happening for 9.1.12 iOS/32 bits.
