### ISSUE TITLE
Failed to load the Frida native extension: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Coldz0** [frida/frida-python#103]
Error
`root@Kali:~# frida

***
Failed to load the Frida native extension: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    load_entry_point('frida==9.1.6', 'console_scripts', 'frida')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/frida-9.1.6-py3.6-linux-i686.egg/frida/__init__.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/frida-9.1.6-py3.6-linux-i686.egg/frida/__init__.py", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/frida-9.1.6-py3.6-linux-i686.egg/_frida.py", line 7, in <module>
  File "/usr/local/lib/python3.6/site-packages/frida-9.1.6-py3.6-linux-i686.egg/_frida.py", line 6, in __bootstrap__
  File "/usr/local/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
root@Kali:~# 

`

**Comment by gdrooid** [comment]
I've installed frida with pip, on python 3.4 and I'm getting the same error.

**Comment by max01203** [comment]
Hi,
I've seen the same problem on python 3.5 I think that you have to use python 3.6 it is the latest stable version of python. 

Thanks

**Comment by oleavr** [comment]
Yes unfortunately our 3.x binaries have only been built against 3.6. It's easy to build Frida yourself though, but if you're feeling really lazy there is a workaround: the Python 3 ABI is stable, so you can use a hex-editor to tweak the version number in the library soname that it's linked against.

**Comment by max01203** [comment]
Good to know thanks for the information :)

**Comment by max01203** [comment]
I think we can close this issue you just need to install python 3.6

**Comment by someOne404** [comment]
I have python 3.6 but got the same problem

**Comment by Josue198s** [comment]
I have python --version Python 3.7.5 and I got the same problem.
