### ISSUE TITLE
frida.TimedOutError: timed out while waiting for device to appear

### ISSUE THREAD

**Issue by illnino** [frida/frida-python#106]
## Problem
It looks like python binding did not work for android device with USB connection. But `frida-ps -U` & **Javascript binding** worked fine.

### ENV

Mac OS: 10.11.6
Android: Samsung Galaxy S6 6.0.1

```bash
➜  frida-learning frida --version
9.1.18
```

```bash
root@zerofltechn:/ # /data/local/tmp/frida-server64 --version
9.1.18
```

## Reproduction Steps

**Error Log:**
```bash
➜  frida-learning python chrome.py
Traceback (most recent call last):
  File "chrome.py", line 21, in <module>
    session = frida.get_usb_device().attach("com.android.chrome")
  File "/Library/Python/2.7/site-packages/frida/__init__.py", line 72, in get_usb_device
    return _get_device(lambda device: device.type == 'tether', timeout)
  File "/Library/Python/2.7/site-packages/frida/__init__.py", line 103, in _get_device
    raise TimedOutError("timed out while waiting for device to appear")
frida.TimedOutError: timed out while waiting for device to appear
```

**Content of chrome.py**
```python
#!/usr/bin/python
import frida

# put your javascript-code here
jscode= """
console.log("[*] Starting script");

Java.perform(function() {
   
   var Activity = Java.use("android.app.Activity");
    Activity.onResume.implementation = function () {
        console.log("[*] onResume() got called!");
        this.onResume();
    };

});

"""

# startup frida and attach to com.android.chrome process on a usb device
session = frida.get_usb_device().attach("com.android.chrome")

# create a script for frida of jsccode
script = session.create_script(jscode)

# and load the script
script.load()

```

### Javascript binding

```bash
➜  frida-learning frida -U -l chrome.js com.android.chrome
     ____
    / _  |   Frida 9.1.18 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Waiting for USB device to appear...

[*] Starting script
[USB::Samsung SM-G9200::com.android.chrome]-> Java
[*] Instance found: android.view.View{6387c27 G.ED..... ......ID 0,0-0,0 #7f0e0207 app:id/action_bar_black_background}
[*] Instance found: android.view.View{90aeed4 V.ED..... ........ 0,2464-0,2464 #7f0e020a app:id/menu_anchor_stub}
[*] Instance found: android.view.View{a64787d G.ED..... ......I. 0,0-0,0 #7f0e0200 app:id/location_bar_verbose_status_separator}
[*] Instance found: android.view.View{72b9372 V.ED..... ......I. 0,572-1440,573}
[*] Finished heap search
{
    "androidVersion": "6.0.1",
    "available": true
}
[USB::Samsung SM-G9200::com.android.chrome]->
```

### frida-ps

```bash
➜  frida-learning frida-ps -U
  PID  Name
-----  --------------------------------------------
13489  adbd
11273  android.process.acore
12146  android.process.media
 3223  androidshmservice
 3092  apaservice
 3103  argosd
 3125  at_distributor
 5681  auditd
...
```

**Comment by mohe2015** [comment]
Same problem for me. Please try to fix that.

**Comment by mohe2015** [comment]
Found out how to fix it: Use `frida.get_usb_device(1)` instead of `frida.get_usb_device()` which adds a small timeout.

**Comment by illnino** [comment]
@mohe2015 It works. Thanks.
