### ISSUE TITLE
Failed to load the Frida native extension on Ubuntu 16.04

### ISSUE THREAD

**Issue by josebeo2016** [frida/frida-python#148]
Hi everyone,
I have a problem when I run frida:
```
***
Failed to load the Frida native extension: /usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so: cannot open shared object file: No such file or directory
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "loader.py", line 2, in <module>
    import frida
  File "/usr/local/lib/python3.6/dist-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: /usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so: cannot open shared object file: No such file or directory
```
But I've checked that the file: ```/usr/local/lib/python3.6/dist-packages/_frida.cpython-36m-arm-linux-gnueabihf.so```
is there:
```
ll /usr/local/lib/python3.6/dist-packages/
total 57660
drwxrwsr-x 6 root staff     4096 Apr  4 02:35 ./
drwxrwsr-x 3 root staff     4096 Apr  4 02:23 ../
-rw-r--r-- 1 root staff 59015804 Apr  4 02:35 _frida.cpython-36m-arm-linux-gnueabihf.so
drwxr-sr-x 3 root staff     4096 Apr  4 02:35 frida/
drwxr-sr-x 2 root staff     4096 Apr  4 02:35 frida-12.4.7.dist-info/
drwxr-sr-x 5 root staff     4096 Apr  4 02:32 pip/
drwxr-sr-x 2 root staff     4096 Apr  4 02:32 pip-19.0.3.dist-info/
```
My system: Ubuntu 16.04 in Odroid.

**Comment by ygsun** [comment]
I found when I use the python binding, I should compile frida extension by myself, You compiled _frida.cpython-36m-arm-linux-gnueabihf.so yourself?

**Comment by ygsun** [comment]
I mean the raspberry pi 3B arm env

**Comment by josebeo2016** [comment]
So what I need is compiling again frida-python on my env? In your case that you compile in raspberry pi 3B arm?

**Comment by ygsun** [comment]
I found when I compiled my frida-python binding, The official source code do not support the armv7a env, But how can you compile _frida.cpython-36m-arm-linux-gnueabihf.so, it looks the same env

**Comment by josebeo2016** [comment]
I see. In my case, I use the original frida-python by using ```pip install python```  and It didn't work. I don't know how to compile it now.

**Comment by ygsun** [comment]
OK, Thanks anyway.
