### ISSUE TITLE
Cannot install frida-tools on raspberry pi

### ISSUE THREAD

**Issue by alexdetrano** [frida/frida-python#152]
I'm using a raspberry pi3b+ with kernel 4.14.98-v7+ .  I try to install frida-tools using pip for python, with Python version 3.5.3. The install works fine on my x86-64 running linux, so I know it's not the version of python. I also tried using pip2 and python 2.7 but I get the same issue. 

```
pi@robopi3bp ~> pip3 install frida-tools
Collecting frida-tools
Collecting prompt-toolkit<3.0.0,>=2.0.0 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl (337kB)
    100% |████████████████████████████████| 337kB 1.3MB/s
Collecting pygments<3.0.0,>=2.0.2 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
    100% |████████████████████████████████| 890kB 1.4MB/s
Collecting colorama<1.0.0,>=0.2.7 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting frida<13.0.0,>=12.5.9 (from frida-tools)
  Downloading https://files.pythonhosted.org/packages/af/6e/9d8e8be84ba93df15a6d68874a5031caf659dba93efa1cf6c3a78d07a4e9/frida-12.6.5.tar.gz
Collecting six>=1.9.0 (from prompt-toolkit<3.0.0,>=2.0.0->frida-tools)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<3.0.0,>=2.0.0->frida-tools)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Building wheels for collected packages: frida
  Running setup.py bdist_wheel for frida ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0vicze89/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__,'exec'))" bdist_wheel -d /tmp/tmpi2zdr6z5pip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.5
  creating build/lib.linux-armv7l-3.5/frida
  copying frida/__init__.py -> build/lib.linux-armv7l-3.5/frida
  copying frida/core.py -> build/lib.linux-armv7l-3.5/frida
  running build_ext
  querying pypi for available prebuilds
  network query failed
  looking for prebuilt extension in home directory, i.e. /home/pi/frida-12.6.5-py3.5-linux-armv7l.egg
  no prebuilt extension found in home directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0vicze89/frida/setup.py", line 183, in <module>
      'build_ext': FridaPrebuiltExt
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 75,in run
      _build_ext.run(self)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-0vicze89/frida/setup.py", line 130, in build_extension
      raise network_error
    File "/tmp/pip-build-0vicze89/frida/setup.py", line 105, in build_extension
      raise Exception("Could not find prebuilt Frida extension. "
  Exception: Could not find prebuilt Frida extension. Prebuilds only provided for Python 2.7 and 3.4+.

  ----------------------------------------
  Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
Installing collected packages: six, wcwidth, prompt-toolkit, pygments, colorama, frida, frida-tools
  Running setup.py install for frida ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0vicze89/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tdobteeq-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.5
    creating build/lib.linux-armv7l-3.5/frida
    copying frida/__init__.py -> build/lib.linux-armv7l-3.5/frida
    copying frida/core.py -> build/lib.linux-armv7l-3.5/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /home/pi/frida-12.6.5-py3.5-linux-armv7l.egg
    no prebuilt extension found in home directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0vicze89/frida/setup.py", line 183, in <module>
        'build_ext': FridaPrebuiltExt
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61,in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-0vicze89/frida/setup.py", line 130, in build_extension
        raise network_error
      File "/tmp/pip-build-0vicze89/frida/setup.py", line 105, in build_extension
        raise Exception("Could not find prebuilt Frida extension. "
    Exception: Could not find prebuilt Frida extension. Prebuilds only provided forPython 2.7 and 3.4+.

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0vicze89/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tdobteeq-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-0vicze89/frida/
```

**Comment by Manouchehri** [comment]
There’s no .egg for Python 3.5 on ARMv7. See https://pypi.org/project/frida/#files

**Comment by oleavr** [comment]
Yes @Manouchehri is correct. This will be addressed at some point, but for now you will have to compile Frida yourself.

**Comment by geekli** [comment]
hi @alexdetrano  how did you install frida on pi successfull?

**Comment by hackdou** [comment]
did the question has be resolved

**Comment by cc5ec** [comment]
I build frida-12.9.8-py3.8-linux-aarch64.egg for raspberry pi running Ubuntu 20.04 64bit.
https://github.com/cc5ec/frida-python-aarch64

**Comment by geekli** [comment]
@cc5ec  py3.5 install failed

> NotImplementedError: could not find prebuilt Frida extension; prebuilds only provided for Python 2.7 and 3.4+

**Comment by CypherpunkArmoury** [comment]
> @cc5ec py3.5 install failed on Raspbian GNU/Linux 9
> 
> > NotImplementedError: could not find prebuilt Frida extension; prebuilds only provided for Python 2.7 and 3.4+

Works for me. I'm using an android device.
you sure you running the installation correctly?
`python3 -m easy_install frida*.egg`

Also, thanks a lot @cc5ec !! Please keep it updated !! :)

**Comment by konsumer** [comment]
How do I compile frida-tools for raspbian? The closest I see is `tools-linux-arm64`, but I don't think that will work.
