### ISSUE TITLE
Failed to install: ```if not path.endswith("/"): TypeError: endswith first arg must be bytes or a tuple of bytes, not str```

### ISSUE THREAD

**Issue by StephanoGeorge** [frida/frida-python#199]
```
Building wheels for collected packages: frida
Building wheel for frida (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l3nj1642
cwd: /tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/
Complete output (53 lines):
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.10
creating build/lib.linux-x86_64-3.10/frida
copying frida/core.py -> build/lib.linux-x86_64-3.10/frida
copying frida/__init__.py -> build/lib.linux-x86_64-3.10/frida
running build_ext
looking for prebuilt extension in home directory, i.e. /home/cheese/frida-15.1.17-py3.10-linux-x86_64.egg
prebuilt extension not found in home directory, will try downloading it
querying pypi for available prebuilds
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/setup.py", line 288, in <module>
setup(
File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
self.run_command('build')
File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
_build_ext.run(self)
File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
self.build_extensions()
File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
_build_ext.build_ext.build_extensions(self)
File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
self._build_extensions_serial()
File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
self.build_extension(ext)
File "/tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/setup.py", line 119, in build_extension
index_url = normalize_url(index_url)
File "/tmp/pip-install-0cevi1sd/frida_bb7091b0747e459aaf96b0bfc55b8afe/setup.py", line 207, in normalize_url
if not path.endswith("/"):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
----------------------------------------
ERROR: Failed building wheel for frida
```

Linux
Python 3.10.2

**Comment by X5tar** [comment]
It's fixed in #197 , but the commit has not been released to PyPI yet.
Try to clone and build it yourself or wait for the maintainers to release the new version.
