### ISSUE TITLE
KeyError: 'Please update your code from `.session.create_script()` to `.create_script()`'

### ISSUE THREAD

**Issue by c0otlass** [frida/frida-python#27]
Hi .
 i  studied this article  
http://blog.mdsec.co.uk/2015/04/instrumenting-android-applications-with.html
and wrote my script to analyze my own simple app.
my script is 
``` python
import frida,sys

def print_result(message):
            print "[*] Testing Toast %s" %(message)
 
def on_message(message, data):
            print_result(message['payload'])
			
jscode = """
 
Dalvik.perform(function () {
   
    var LockManager = Dalvik.use("com.example.fridajavatest.MainActivity");
    var LockManagerInstance = LockManager.ShowToast();
 
    for(var i=1230; i<1235; i++)
    {
            var result = LockManagerInstance.checkPasscode(i+"");
        send(i + ": " + result);
    }
});
"""
 
process = frida.get_device_manager().enumerate_devices()[-1].attach("com.example.fridajavatest")
session = process.session
 
script = session.create_script(jscode)
script.on('message', on_message)
script.load()
sys.stdin.read()
```
then i run it
```
$ python JavaTest.py 
Traceback (most recent call last):
  File "JavaTest.py", line 25, in <module>
    session = process.session
  File "/Library/Python/2.7/site-packages/frida-3.0.1-py2.7-macosx-10.9-intel.egg/frida/core.py", line 209, in __getattr__
KeyError: 'Please update your code from `.session.create_script()` to `.create_script()`'
```
could you guide me ..... what is the problem?
best regards

**Comment by oleavr** [comment]
Hi,

This is because the Frida API changed in the new major version, and you need to update this:

```python
process = frida.get_device_manager().enumerate_devices()[-1].attach("com.example.fridajavatest")
session = process.session
```

to:
```python
session = frida.get_device_manager().enumerate_devices()[-1].attach("com.example.fridajavatest")
```

Cheers!

**Comment by c0otlass** [comment]
thanks you ...
my problem solved ....

**Comment by oleavr** [comment]
Glad to hear. Thanks for using Frida!
