### ISSUE TITLE
Failed to load the Frida native extension on linux

### ISSUE THREAD

**Issue by beyhaqi** [frida/frida-python#28]
hi
I have install frida via easy_install on my computer but I have an error when executing this command:
$frida-ps -R
the result is the below error:

 
Failed to load the Frida native extension: /home/user/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
Please ensure that the extension was compiled for Python 2.7.
***	

Traceback (most recent call last):
  File "/usr/local/bin/frida-ps", line 8, in <module>
    load_entry_point('frida==3.0.1', 'console_scripts', 'frida-ps')()
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/ps.py", line 58, in main
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/application.py", line 81, in run
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/__init__.py", line 84, in get_device_manager
ImportError: /home/user/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

my OS : Ubuntu 14.04 x64, Python version 2.7

**Comment by beyhaqi** [comment]
sorry 
my OS : Ubuntu 14.04 x64, Python version 2.7

**Comment by oleavr** [comment]
Hi,

This is a known issue with the currently released Linux binaries, and will be fixed in the upcoming release. In the meantime you will unfortunately have to build Frida yourself on Linux (the binaries for the other OSes are OK). Sorry about the inconvenience!

Cheers!
