### ISSUE TITLE
check-python-64: remote_exec PTRACE_CONT wait failed

### ISSUE THREAD

**Issue by v-p-b** [frida/frida-python#29]
master branch builds successfully (latest commit: 8514bd84912fb213adc1de82c689df55cc99dcd4), but python binding tests fail with the following error:

```
$ sudo sysctl kernel.yama.ptrace_scope
kernel.yama.ptrace_scope = 0
$ make check-python-64
make[1]: Entering directory `/path/frida'
export PYTHONPATH="/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages" \
		&& cd frida-python \
		&& /usr/bin/python -m unittest tests.test_core tests.test_tracer
.......E
======================================================================
ERROR: setUpClass (tests.test_tracer.TestTracer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_tracer.py", line 24, in setUpClass
    cls.session = frida.attach(cls.target.pid)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/__init__.py", line 40, in attach
    return get_device_manager().get_device(device_id).attach(target)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/core.py", line 69, in attach
    return Session(self._impl.attach(self._pid_of(target)))
SystemError: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: remote_exec PTRACE_CONT wait failed: 0

----------------------------------------------------------------------
Ran 7 tests in 0.339s

FAILED (errors=1)
make[1]: *** [check-python-64] Error 1
make[1]: Leaving directory `/path/frida'
make: *** [check-python-64] Error 2
```

**Comment by oleavr** [comment]
This should now be fixed in latest master with a proper error message explaining how to tweak system settings. Thanks!

**Comment by v-p-b** [comment]
I get a different error message now:

```
$ make check-python-64
make[1]: Entering directory `/path/frida'
export PYTHONPATH="/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages" \
		&& cd frida-python \
		&& /usr/bin/python -m unittest tests.test_core tests.test_tracer
EE
======================================================================
ERROR: setUpClass (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_core.py", line 23, in setUpClass
    cls.session = frida.attach(cls.target.pid)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/__init__.py", line 40, in attach
    return get_device_manager().get_device(device_id).attach(target)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/core.py", line 69, in attach
    return Session(self._impl.attach(self._pid_of(target)))
SystemError: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: attach_to_process PTRACE_GETREGS failed: 3

======================================================================
ERROR: setUpClass (tests.test_tracer.TestTracer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_tracer.py", line 24, in setUpClass
    cls.session = frida.attach(cls.target.pid)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/__init__.py", line 40, in attach
    return get_device_manager().get_device(device_id).attach(target)
  File "/path/frida/build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida/core.py", line 69, in attach
    return Session(self._impl.attach(self._pid_of(target)))
SystemError: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: attach_to_process PTRACE_GETREGS failed: 3

----------------------------------------------------------------------
Ran 0 tests in 0.094s

FAILED (errors=2)
make[1]: *** [check-python-64] Error 1
make[1]: Leaving directory `/path/frida'
make: *** [check-python-64] Error 2
```

Are the mentioned system setting tweaks documented somewhere?

**Comment by oleavr** [comment]
Your source tree seems to be outdated; try `git submodule update` after `git pull` in the “frida” module. It will give you a very different error message, and a snippet you can copy-paste to tweak your running kernel.

**Comment by oleavr** [comment]
(It's documented in the Troubleshooting section on the website, but that will be removed soon as the error message covers it.)

**Comment by v-p-b** [comment]
Strange, as you can see in the first comment, the kernel.yama.ptrace_scope was set as described. Anyway, now after doing the submodule update (stupid mistake, sorry) and fixed a unicode error (see https://github.com/frida/frida-python/pull/31) the check runs without problems, thank you!

**Comment by oleavr** [comment]
Ah, good to hear. Thanks for investigating!
