### ISSUE TITLE
frida-ps on El Capitan

### ISSUE THREAD

**Issue by progopis** [frida/frida-python#56]
I get next errors each time using frida-ps:
```...
 287  iTerm
 834  iTunes Helper
 100  loginwindow
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/frida-6.0.1-py2.7-macosx-10.9-intel.egg/frida/application.py", line 333, in _run
    work()
  File "/Library/Python/2.7/site-packages/frida-6.0.1-py2.7-macosx-10.9-intel.egg/frida/application.py", line 223, in _try_start
    self._start()
  File "/Library/Python/2.7/site-packages/frida-6.0.1-py2.7-macosx-10.9-intel.egg/frida/ps.py", line 68, in _start
    self._print(line_format % (process.pid, process.name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
```

I created a quick fix for it:
```
 ➜  frida git:(master) ✗ diff ps.py ps_new.py
68c68
<                     self._print(line_format % (process.pid, process.name))
---
>                     self._print(line_format % (process.pid, process.name.decode("utf8")))
```

And the reason is some utf8 processes:
```
 289  µTorrent
 869  Центр уведомлений
```

**Comment by oleavr** [comment]
Ahh nice catch! `process.name` should be unicode, so this is a bug in the binding itself. Thanks!

**Comment by progopis** [comment]
I checked frida/frida-core/src/darwin/system-darwin.m:
I found this place in source:
```info->_name = g_strdup ([app.localizedName UTF8String]);```
It looks fair and unicode compliant

I added a new pull request, cause it really fixes a problem for me and my friend. So, on your decision ;)

**Comment by progopis** [comment]
https://github.com/frida/frida-python/pull/58

**Comment by oleavr** [comment]
Again thanks a lot for digging into this! I fixed this in 0de6b5315de6758a5d3f61fbd24a90967bbc7c5b, where the Python 2.x now exposes UTF-8 strings as unicode objects, which is consistent with how we expose them as (proper) strings on Python 3.x. The build machines are now chewing on 6.0.2 containing this fix.

**Comment by oleavr** [comment]
Frida 6.0.2 is out with this fix, please let me know if there's any further issues!

**Comment by progopis** [comment]
It works nice now, big thanks!
